openapi: 3.0.0
info:
  title: Elysia API
  version: 1.0.0
paths:
  /{name}:
    get:
      summary: Get a personalized greeting
      description: Returns a greeting message with the provided name.
      parameters:
        - in: path
          name: name
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            text/plain:
              schema:
                type: string
      '404':
        description: Not Found