apiVersion: core.choreo.dev/v1alpha1
kind: ComponentConfig
metadata:
    name: tesdodcc
    projectName: Default Project
    annotations:
        componentType: service
spec:
    build:
        branch: main
    inbound:
        - name: tesdODcc
          port: 9090
          type: REST
          visibility: Project
          context: /
