apiVersion: core.choreo.dev/v1alpha1
kind: ComponentConfig
metadata:
    name: bal-proj-dep-test
    projectName: Default Project
    annotations:
        componentType: service
spec:
    build:
        branch: main
    inbound:
        - name: bal-proj-dep-test
          port: 9090
          type: REST
          visibility: Public
          context: /
